### ISSUE TITLE
Создать компонент карточки предмета

### ISSUE THREAD

**Issue by qqpayne** [CyberDAS-Dev/VK_marketplace#2]
Самый важный компонент, который будет составлять основу ленты объявлений

Должен содержать следующие элементы:
- До 10 фотографий, с возможность их скроллить (https://vkcom.github.io/VKUI/#/Gallery). При нажатии на карусель, фотографии должны расширяться для просмотра их в полный размер
- Заголовок, в 'bold' начертании и большим шрифтом
- Короткое описание
- Цену, которая в некоторых случаях может заменяться на строки "Бесплатно" и "За шоколадку"
- Кнопку раскрытия объявления в полный размер

С этими пунктами (скорее всего) поможет https://vkcom.github.io/VKUI/#/ContentCard

Примерный вид:
![image](https://user-images.githubusercontent.com/43206835/136701743-e0df7645-1026-420c-99a8-4e1709746833.png)

После нажатия кнопки раскрытия:
- Описание должно заменяться полным
- Цена превращается в кнопку, предлагающую пользователю купить предметь\забрать его бесплатно

Примерный вид (фото здесь не должно быть увеличеным по сравнению с предыдущей фотографией):
![image](https://user-images.githubusercontent.com/43206835/136701829-a916293a-38f0-4e3f-8b1e-7338e27faabd.png)

**Comment by idonotknowwhoiam** [comment]
>Цену, которая в некоторых случаях может заменяться на строки "Бесплатно" и "За шоколадку"
Было решено изменить "За шоколадку" на договорную цену.
